#all()
tp = ()
tp1 = (1,2)
tp2 = (0,False,False)
tp3 = (True,True,True)
tp4 = (1,True,True)
tp5 = (0,True,True)
print("all() of empty tuple is ", all(tp))
print(f'all() of {tp1} is {all(tp1)}')
print(all(tp2))
print(all(tp3))
print(all(tp4))
print(all(tp5))
